### PR TITLE
Add protocol file for 92440 

### PR DESCRIPTION
**Pull request by y13i**
Adding protocol file for new SC2 patch.

Verified with the CLI as below:

```
go run cmd/s2prot/s2prot.go ./Oceanborn\ LE\ \(109\).SC2Replay # new version's replay
```

### CODE REVIEW

**Comment by icza** [comment]
Thanks for the PR.

**Comment by bdibbell** [comment]
hiya, any chance of a release for this?

**Comment by icza** [comment]
There you go, created release [v1.5.2](https://github.com/icza/s2prot/releases/tag/v1.5.2)

**Comment by bdibbell** [comment]
thanks so much 👍

**Pull request merged**
