### PR TITLE
Use new depot URLs introduced in 5.0.5 && go fmt, lint and fix typo

### PR DESCRIPTION
**Pull request by NaniteFactory**

### CODE REVIEW

**Comment by amartin916** [comment]
Both urls will need to be supported for older replays, this pull requests scares me it might break older replays

**Comment by icza** [comment]
The new URL's don't support the old contents? Are they not a replacement of the old URLs?

**Comment by NaniteFactory** [comment]
I think the new URL replaces the legacy one. [This](https://sc2arcade.com/map/2/103675/) is a map from 2011 which is quite old, and both links seem to work.

http://eu.depot.battle.net:1119/6d80dfb0bc2b596479dd60f430b720ecb121fd29510299fbc094d87e1fc53e70.s2mh
https://eu-s2-depot.classic.blizzard.com/6d80dfb0bc2b596479dd60f430b720ecb121fd29510299fbc094d87e1fc53e70.s2mh

http://eu.depot.battle.net:1119/cd52c5e961bc37a0681231ce286ecc290123fe0dc5ba413227e4985df7e53a34.s2ma
https://eu-s2-depot.classic.blizzard.com/cd52c5e961bc37a0681231ce286ecc290123fe0dc5ba413227e4985df7e53a34.s2ma

**Comment by amartin916** [comment]
I might be mistaken on what this did, I thought it was used for lookups inside the code but skimming it i'm not seeing that. its its only used for returning the url then nm, on my first comment :)

**Comment by icza** [comment]
In thank case thanks for the PR.

**Pull request merged**
